#!/bin/bash

opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}')"
clear
echo -e ""
echo -e " == EkelamOsus == "
echo -e ""
echo -e " OpenSSH Port: 22"$opensshport
echo -e " Dropbear Port: 442"$dropbearport
echo -e " SSL Port: 443"$stunnel4port
echo -e " Squid Ports: 8118"$squidport
echo -e " OpenVPN Port: "$openvpnport
echo -e ""
